version: "3"

services:
  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # api:
  #   container_name: api
  #   image: api
  #   build: .
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres:postgres-container
  #   restart: on-failure

volumes:
  db: 
    